backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "src/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter. 
    # Remove any that aren't needed for posts
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Project Name", name: "projectName", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Date", name: "date", widget: "string"}
      # - {label: "Techs", name: "techs", widget: "list" }
      # - {label: "Images", name: "img", widget: "list" }